# =============================================================================
# rp_user BD for the au50 flow_reduce app (UDP Vector-Averaging NF).
# Packaged-shell flow + current dual-downstream RP stream contract.
#
# Topology:
#   s_axis_rph2c ─►[guard]─┐
#   s_axis_ethrx0─►[guard]─┴► rp_in_sw (2:1) ─► nf_0/s_axis_rpin
#   nf_0/m_axis_rpout ─► rp_out_sw (1:2, tdest[15]) ─┬►[guard]─► m_axis_rpout0 (C2H)
#                                                    └►[guard]─► m_axis_rpout1
#   s_axil ─►[guard]─► axil_sc (1 SI × 3 MI) ─► { nf_0/s_axil ; apb_bridge_hbm
#                                       ─► hbm_0/SAPB_0 ; axi_gpio_0 (status) }
#   nf_0/hbm_axi_{0,1,2} ─┐
#                          ├─► hbm_sc_NN (2:1) ─► path_NN ─► hbm_0/SAXI_NN
#   s_axi_dma ─►[guard]─► dma_sc (1 SI × 3 MI) ─┘  (host pre-loads reference
#                                       vectors; NF issues read-only reads)
#   nf_0/m_axibr ─► m_axibr (direct, host notification ring — DRIVEN)
#   s_axi_pcie ─►[guard]─► scratch_sc ─► scratch_bram_ctrl (4 KB BAR4 scratchpad)
#   hbm_0/SAXI_{01,03,05} ─ null-tied internally (PC1 of MC0..2)
#
# HBM IP: 1 stack (LEFT), 4 GB, MCs 0..2 (channels 0/2/4 -> SAXI_00/02/04), ECC
# bypass, lateral switch OFF. HBM clocks are generated by the in-BD Clocking
# Wizard hbm_mmcm_i0 (100M ref / 100M APB / 450M AXI from free_100m_clk/RST_N) --
# rp_blk.v is fixed/shell-supplied and no longer hosts app RTL.
#
# Boundary guard register slices (axi_regsl_dma/pcie, axil_regsl,
# axis_regsl_rph2c/ethrx0/rpout0/rpout1) are pinned into EXCLUDE_PLACEMENT guard
# pblocks by floorplan.xdc to close timing -- same technique as hbm_loopback.
#
# Per-channel path_NN (verbatim from hbm_loopback): regsl_entry(@user,REG=10,
# SLR-crossing) -> clk_conv(CDC user->hbm) -> slice_b(@hbm,REG=7) ->
# dwidth_conv(512->256) -> regsl_rama(REG=7) -> rama(reorder) -> hbm_0/SAXI_NN.
# =============================================================================

# -----------------------------------------------------------------------------
# Hier: path_NN — user_clk/512b AXI4 -> hbm_axiclk/256b AXI4 with reorder buffer
# (identical to app/hbm_loopback/rp_user.tcl)
# -----------------------------------------------------------------------------
proc create_hier_cell_path { parentCell nameHier } {

  if { $parentCell eq "" || $nameHier eq "" } {
    catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" \
        "create_hier_cell_path() - Empty argument(s)!"}
    return
  }

  set parentObj [get_bd_cells $parentCell]
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
    catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" \
        "Parent <$parentObj> has TYPE = <$parentType>. Expected <hier>."}
    return
  }

  set oldCurInst [current_bd_instance .]
  current_bd_instance $parentObj
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  create_bd_intf_pin -mode Slave  -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI
  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M_AXI

  create_bd_pin -dir I -type clk aclk_user
  create_bd_pin -dir I -type rst aresetn_user
  create_bd_pin -dir I -type clk aclk_hbm
  create_bd_pin -dir I -type rst aresetn_hbm

  set regsl_entry [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_register_slice:2.1 regsl_entry]
  set_property -dict [list \
    CONFIG.REG_AR {10} CONFIG.REG_AW {10} CONFIG.REG_B {10} \
    CONFIG.REG_R  {10} CONFIG.REG_W  {10} \
  ] $regsl_entry

  set clk_conv [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_clock_converter:2.1 clk_conv]

  set slice_b [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_register_slice:2.1 slice_b]
  set_property -dict [list \
    CONFIG.REG_AR {7} CONFIG.REG_AW {7} CONFIG.REG_B {7} \
    CONFIG.REG_R  {7} CONFIG.REG_W  {7} \
  ] $slice_b

  set dwidth_conv [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dwidth_converter:2.1 dwidth_conv]
  set_property -dict [list \
    CONFIG.SI_DATA_WIDTH.VALUE_SRC USER \
    CONFIG.MI_DATA_WIDTH.VALUE_SRC USER \
    CONFIG.SI_DATA_WIDTH {512} \
    CONFIG.MI_DATA_WIDTH {256} \
  ] $dwidth_conv

  set regsl_rama [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_register_slice:2.1 regsl_rama]
  set_property -dict [list \
    CONFIG.REG_AR {7} CONFIG.REG_AW {7} CONFIG.REG_B {7} \
    CONFIG.REG_R  {7} CONFIG.REG_W  {7} \
  ] $regsl_rama

  set rama [create_bd_cell -type ip -vlnv xilinx.com:ip:rama:1.1 rama]
  set_property -dict [list \
    CONFIG.G_MEM_INTERLEAVE_TYPE {per_memory} \
    CONFIG.G_MEM_COUNT           {32} \
    CONFIG.G_REORDER_QUEUE_DEPTH {512} \
  ] $rama

  connect_bd_intf_net [get_bd_intf_pins S_AXI]              [get_bd_intf_pins regsl_entry/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins regsl_entry/M_AXI]  [get_bd_intf_pins clk_conv/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins clk_conv/M_AXI]     [get_bd_intf_pins slice_b/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins slice_b/M_AXI]      [get_bd_intf_pins dwidth_conv/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins dwidth_conv/M_AXI]  [get_bd_intf_pins regsl_rama/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins regsl_rama/M_AXI]   [get_bd_intf_pins rama/s_axi]
  connect_bd_intf_net [get_bd_intf_pins rama/m_axi]         [get_bd_intf_pins M_AXI]

  connect_bd_net [get_bd_pins aclk_user] \
    [get_bd_pins regsl_entry/aclk] \
    [get_bd_pins clk_conv/s_axi_aclk]
  connect_bd_net [get_bd_pins aresetn_user] \
    [get_bd_pins regsl_entry/aresetn] \
    [get_bd_pins clk_conv/s_axi_aresetn]
  connect_bd_net [get_bd_pins aclk_hbm] \
    [get_bd_pins clk_conv/m_axi_aclk] \
    [get_bd_pins slice_b/aclk] \
    [get_bd_pins dwidth_conv/s_axi_aclk] \
    [get_bd_pins regsl_rama/aclk] \
    [get_bd_pins rama/axi_aclk]
  connect_bd_net [get_bd_pins aresetn_hbm] \
    [get_bd_pins clk_conv/m_axi_aresetn] \
    [get_bd_pins slice_b/aresetn] \
    [get_bd_pins dwidth_conv/s_axi_aresetn] \
    [get_bd_pins regsl_rama/aresetn] \
    [get_bd_pins rama/axi_aresetn]

  current_bd_instance $oldCurInst
}

# -----------------------------------------------------------------------------
# Main BD: rp_user
# -----------------------------------------------------------------------------
proc cr_bd_rp_user { parentCell } {

  set design_name rp_user
  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" \
      "Creating BD <$design_name>..."

  create_bd_design $design_name

  set list_check_ips "\
    nus.edu.sg:bsv:mkVectorAvgNF:1.0\
    xilinx.com:ip:hbm:1.0\
    xilinx.com:ip:clk_wiz:6.0\
    xilinx.com:ip:smartconnect:1.0\
    xilinx.com:ip:axi_register_slice:2.1\
    xilinx.com:ip:axis_register_slice:1.1\
    xilinx.com:ip:axi_clock_converter:2.1\
    xilinx.com:ip:axi_dwidth_converter:2.1\
    xilinx.com:ip:rama:1.1\
    xilinx.com:ip:axi_apb_bridge:3.0\
    xilinx.com:ip:axi_gpio:2.0\
    xilinx.com:ip:axi_bram_ctrl:4.1\
    xilinx.com:ip:blk_mem_gen:8.4\
    xilinx.com:ip:axis_switch:1.1\
    xilinx.com:ip:xlconcat:2.1\
    xilinx.com:ip:xlconstant:1.1\
    xilinx.com:ip:proc_sys_reset:5.0\
  "
  set list_ips_missing ""
  foreach ip_vlnv $list_check_ips {
    if { [get_ipdefs -all $ip_vlnv] eq "" } {
      lappend list_ips_missing $ip_vlnv
    }
  }
  if { $list_ips_missing ne "" } {
    catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" \
        "Missing IPs in catalog:\n  $list_ips_missing"}
    return 3
  }

  if { $parentCell eq "" } { set parentCell [get_bd_cells /] }
  set parentObj [get_bd_cells $parentCell]
  set oldCurInst [current_bd_instance .]
  current_bd_instance $parentObj

  # ===========================================================================
  # External interface ports (match the shell-supplied rp_blk.v contract)
  # ===========================================================================
  set s_axi_dma [create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 s_axi_dma]
  set_property -dict [list \
    CONFIG.ADDR_WIDTH        {64} \
    CONFIG.DATA_WIDTH        {512} \
    CONFIG.ID_WIDTH          {2} \
    CONFIG.PROTOCOL          {AXI4} \
    CONFIG.FREQ_HZ           {200000000} \
    CONFIG.MAX_BURST_LENGTH  {1} \
    CONFIG.NUM_READ_OUTSTANDING  {1} \
    CONFIG.NUM_WRITE_OUTSTANDING {1} \
    CONFIG.READ_WRITE_MODE   {READ_WRITE} \
    CONFIG.HAS_BRESP         {1} CONFIG.HAS_RRESP {1} CONFIG.HAS_WSTRB {1} \
    CONFIG.HAS_BURST         {1} CONFIG.HAS_CACHE {1} CONFIG.HAS_LOCK {1} \
    CONFIG.HAS_PROT          {1} CONFIG.HAS_QOS   {1} CONFIG.HAS_REGION {1} \
    CONFIG.SUPPORTS_NARROW_BURST {0} \
  ] $s_axi_dma

  set s_axi_pcie [create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 s_axi_pcie]
  set_property -dict [list \
    CONFIG.ADDR_WIDTH        {64} \
    CONFIG.DATA_WIDTH        {512} \
    CONFIG.ID_WIDTH          {2} \
    CONFIG.PROTOCOL          {AXI4} \
    CONFIG.FREQ_HZ           {200000000} \
    CONFIG.MAX_BURST_LENGTH  {1} \
    CONFIG.NUM_READ_OUTSTANDING  {1} \
    CONFIG.NUM_WRITE_OUTSTANDING {1} \
    CONFIG.READ_WRITE_MODE   {READ_WRITE} \
    CONFIG.HAS_BRESP         {1} CONFIG.HAS_RRESP {1} CONFIG.HAS_WSTRB {1} \
    CONFIG.HAS_BURST         {1} CONFIG.HAS_CACHE {1} CONFIG.HAS_LOCK {1} \
    CONFIG.HAS_PROT          {1} CONFIG.HAS_QOS   {1} CONFIG.HAS_REGION {1} \
    CONFIG.SUPPORTS_NARROW_BURST {0} \
  ] $s_axi_pcie

  set s_axil [create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 s_axil]
  set_property -dict [list \
    CONFIG.ADDR_WIDTH {32} CONFIG.DATA_WIDTH {32} \
    CONFIG.PROTOCOL {AXI4LITE} CONFIG.FREQ_HZ {200000000} \
    CONFIG.HAS_BRESP {1} CONFIG.HAS_RRESP {1} CONFIG.HAS_WSTRB {0} \
    CONFIG.HAS_BURST {0} CONFIG.HAS_CACHE {0} CONFIG.HAS_LOCK {0} \
    CONFIG.HAS_PROT  {0} CONFIG.HAS_QOS  {0} CONFIG.HAS_REGION {0} \
  ] $s_axil

  # AXIS ingress (dual): host H2C lane + NIC RX lane. Same shape as rp_blk.v.
  foreach ax {s_axis_rph2c s_axis_ethrx0} {
    set p [create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 $ax]
    set_property -dict [list \
      CONFIG.FREQ_HZ {200000000} \
      CONFIG.TDATA_NUM_BYTES {64} \
      CONFIG.TDEST_WIDTH {16} CONFIG.TID_WIDTH {16} CONFIG.TUSER_WIDTH {32} \
      CONFIG.HAS_TKEEP {1} CONFIG.HAS_TLAST {1} CONFIG.HAS_TSTRB {1} CONFIG.HAS_TREADY {1} \
    ] $p
  }

  # AXIS egress (dual): shape inferred from the driving guard slice.
  set m_axis_rpout0 [create_bd_intf_port -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 m_axis_rpout0]
  set_property CONFIG.FREQ_HZ {200000000} $m_axis_rpout0
  set m_axis_rpout1 [create_bd_intf_port -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 m_axis_rpout1]
  set_property CONFIG.FREQ_HZ {200000000} $m_axis_rpout1

  # m_axibr — DRIVEN by the NF (notification-ring writeback to host PCIe).
  # Connected DIRECTLY to nf_0/m_axibr (no SmartConnect): a 1x1 SC strips the
  # transaction-ID ports, leaving the external port ID-width 0 while the
  # rp_blk.v contract drives 4-bit IDs. Direct connection makes the external
  # port inherit nf_0/m_axibr's exact 4,64,512 shape. rp_blk.v's m_axibr port
  # list is a subset (no cache/lock/prot/qos/region); those extra wrapper ports
  # are simply left unconnected -> benign Synth 8-7071 warnings.
  # ID_WIDTH is inferred (read-only) from the direct nf_0/m_axibr connection --
  # the NF master is 4-id/64-addr/512-data full-AXI4, matching rp_blk.v -- so it
  # is NOT set here (setting it triggers a benign BD 41-737 read-only warning).
  # The /m_axibr/Reg segment stays unassigned in nf_0/m_axibr's space (BD
  # 41-1356): harmless for a direct 1:1 master->port connection -- the NF's
  # awaddr[63:0] passes straight through, no crossbar decode.
  set m_axibr [create_bd_intf_port -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 m_axibr]
  set_property -dict [list \
    CONFIG.ADDR_WIDTH {64} \
    CONFIG.DATA_WIDTH {512} \
    CONFIG.PROTOCOL   {AXI4} \
    CONFIG.FREQ_HZ    {200000000} \
    CONFIG.HAS_BURST  {1} CONFIG.HAS_BRESP {1} CONFIG.HAS_RRESP {1} \
    CONFIG.HAS_WSTRB  {1} CONFIG.HAS_CACHE {1} CONFIG.HAS_LOCK {1} \
    CONFIG.HAS_PROT   {1} CONFIG.HAS_QOS  {1} CONFIG.HAS_REGION {1} \
  ] $m_axibr

  # Clock/reset ports
  set CLK [create_bd_port -dir I -type clk -freq_hz 200000000 CLK]
  set_property -dict [list \
    CONFIG.ASSOCIATED_BUSIF {s_axil:s_axi_dma:s_axi_pcie:s_axis_rph2c:s_axis_ethrx0:m_axis_rpout0:m_axis_rpout1:m_axibr} \
    CONFIG.ASSOCIATED_RESET {RST_N} \
  ] $CLK
  set RST_N [create_bd_port -dir I -type rst RST_N]
  set_property CONFIG.POLARITY ACTIVE_LOW $RST_N

  set free_100m_clk [create_bd_port -dir I -type clk -freq_hz 100000000 free_100m_clk]

  # ===========================================================================
  # HBM clock generator — Clocking Wizard (100M ref / 100M APB / 450M AXI).
  # Catalog IP: pins come pre-typed with correct FREQ_HZ from
  # CLKOUTn_REQUESTED_OUT_FREQ, so no X_INTERFACE_INFO annotation is needed.
  # rp_blk.v is fixed/shell-supplied and has no HBM-clock ports to source these
  # from -- the generator lives in the BD.
  # ===========================================================================
  set hbm_mmcm_i0 [create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 hbm_mmcm_i0]
  set_property -dict [list \
    CONFIG.PRIM_IN_FREQ            {100.000} \
    CONFIG.PRIM_SOURCE             {No_buffer} \
    CONFIG.CLKIN1_JITTER_PS        {100.0} \
    CONFIG.CLK_OUT1_PORT           {hbm_refclk} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {100.000} \
    CONFIG.CLK_OUT2_PORT           {hbm_apbclk} \
    CONFIG.CLKOUT2_USED            {true} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {100.000} \
    CONFIG.CLK_OUT3_PORT           {hbm_axiclk} \
    CONFIG.CLKOUT3_USED            {true} \
    CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {450.000} \
    CONFIG.NUM_OUT_CLKS            {3} \
    CONFIG.CLKOUT1_DRIVES          {BUFG} \
    CONFIG.CLKOUT2_DRIVES          {BUFG} \
    CONFIG.CLKOUT3_DRIVES          {BUFG} \
    CONFIG.USE_LOCKED              {true} \
    CONFIG.USE_RESET               {true} \
    CONFIG.RESET_TYPE              {ACTIVE_LOW} \
  ] $hbm_mmcm_i0
  connect_bd_net [get_bd_ports free_100m_clk] [get_bd_pins hbm_mmcm_i0/clk_in1]
  connect_bd_net [get_bd_ports RST_N]         [get_bd_pins hbm_mmcm_i0/resetn]

  # ===========================================================================
  # Resets for HBM domains
  # ===========================================================================
  set hbm_proc_rst [create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 hbm_proc_rst]
  set apb_proc_rst [create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 apb_proc_rst]

  # ===========================================================================
  # HBM IP — 1 stack (LEFT), 4 GB, MCs 0..2 enabled, ECC bypass, switch off
  # ===========================================================================
  set hbm_0 [create_bd_cell -type ip -vlnv xilinx.com:ip:hbm:1.0 hbm_0]
  set_property -dict [list \
    CONFIG.USER_HBM_DENSITY             {4GB} \
    CONFIG.USER_HBM_STACK               {1} \
    CONFIG.USER_SINGLE_STACK_SELECTION  {LEFT} \
    CONFIG.USER_MEMORY_DISPLAY          {4096} \
    CONFIG.USER_AUTO_POPULATE           {yes} \
    CONFIG.USER_DIS_REF_CLK_BUFG        {TRUE} \
    CONFIG.USER_DEBUG_EN                {FALSE} \
    CONFIG.USER_XSDB_INTF_EN            {FALSE} \
    CONFIG.USER_APB_EN                  {true} \
    CONFIG.USER_INIT_TIMEOUT_VAL        {0} \
    CONFIG.USER_HBM_REF_CLK_0           {100} \
    CONFIG.USER_AXI_CLK_FREQ            {450} \
    CONFIG.USER_AXI_INPUT_CLK_FREQ      {450} \
    CONFIG.USER_SWITCH_ENABLE_00        {FALSE} \
    CONFIG.USER_CLK_SEL_LIST0           {AXI_15_ACLK} \
    CONFIG.USER_MC_ENABLE_00            {TRUE} \
    CONFIG.USER_MC_ENABLE_01            {TRUE} \
    CONFIG.USER_MC_ENABLE_02            {TRUE} \
    CONFIG.USER_MC_ENABLE_03            {FALSE} \
    CONFIG.USER_MC_ENABLE_04            {FALSE} \
    CONFIG.USER_MC_ENABLE_05            {FALSE} \
    CONFIG.USER_MC_ENABLE_06            {FALSE} \
    CONFIG.USER_MC_ENABLE_07            {FALSE} \
    CONFIG.USER_MC_ENABLE_APB_00        {TRUE} \
    CONFIG.USER_PHY_ENABLE_00           {TRUE} \
    CONFIG.USER_PHY_ENABLE_01           {TRUE} \
    CONFIG.USER_PHY_ENABLE_02           {TRUE} \
    CONFIG.USER_PHY_ENABLE_03           {FALSE} \
    CONFIG.USER_PHY_ENABLE_04           {FALSE} \
    CONFIG.USER_PHY_ENABLE_05           {FALSE} \
    CONFIG.USER_PHY_ENABLE_06           {FALSE} \
    CONFIG.USER_PHY_ENABLE_07           {FALSE} \
    CONFIG.USER_MC0_ECC_BYPASS          {true} \
    CONFIG.USER_MC1_ECC_BYPASS          {true} \
    CONFIG.USER_MC2_ECC_BYPASS          {true} \
  ] $hbm_0

  # ===========================================================================
  # Null-tie the unused HBM SAXI ports (PC1 of each enabled MC: 01,03,05).
  # Only PC0 (00,02,04) is driven from the SmartConnect/path_NN; PC1 still needs
  # a legally-idle AXI3 master or the HBM controller stalls. Wired directly to
  # hbm_0's flattened physical pins (AXI_NN_<SIGNAL>) -- no external port needed.
  # ===========================================================================
  set toff_zero_1b   [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_zero_1b]
  set_property -dict [list CONFIG.CONST_WIDTH 1 CONFIG.CONST_VAL 0] $toff_zero_1b
  set toff_one_1b    [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_one_1b]
  set_property -dict [list CONFIG.CONST_WIDTH 1 CONFIG.CONST_VAL 1] $toff_one_1b
  set toff_zero_2b   [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_zero_2b]
  set_property -dict [list CONFIG.CONST_WIDTH 2 CONFIG.CONST_VAL 0] $toff_zero_2b
  set toff_zero_3b   [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_zero_3b]
  set_property -dict [list CONFIG.CONST_WIDTH 3 CONFIG.CONST_VAL 0] $toff_zero_3b
  set toff_zero_4b   [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_zero_4b]
  set_property -dict [list CONFIG.CONST_WIDTH 4 CONFIG.CONST_VAL 0] $toff_zero_4b
  set toff_zero_6b   [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_zero_6b]
  set_property -dict [list CONFIG.CONST_WIDTH 6 CONFIG.CONST_VAL 0] $toff_zero_6b
  set toff_zero_32b  [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_zero_32b]
  set_property -dict [list CONFIG.CONST_WIDTH 32 CONFIG.CONST_VAL 0] $toff_zero_32b
  set toff_zero_33b  [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_zero_33b]
  set_property -dict [list CONFIG.CONST_WIDTH 33 CONFIG.CONST_VAL 0] $toff_zero_33b
  set toff_zero_256b [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 toff_zero_256b]
  set_property -dict [list CONFIG.CONST_WIDTH 256 CONFIG.CONST_VAL 0] $toff_zero_256b

  foreach saxi {01 03 05} {
    connect_bd_net [get_bd_pins $toff_zero_33b/dout]  [get_bd_pins hbm_0/AXI_${saxi}_ARADDR]
    connect_bd_net [get_bd_pins $toff_zero_2b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_ARBURST]
    connect_bd_net [get_bd_pins $toff_zero_6b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_ARID]
    connect_bd_net [get_bd_pins $toff_zero_4b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_ARLEN]
    connect_bd_net [get_bd_pins $toff_zero_3b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_ARSIZE]
    connect_bd_net [get_bd_pins $toff_zero_1b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_ARVALID]
    connect_bd_net [get_bd_pins $toff_zero_33b/dout]  [get_bd_pins hbm_0/AXI_${saxi}_AWADDR]
    connect_bd_net [get_bd_pins $toff_zero_2b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_AWBURST]
    connect_bd_net [get_bd_pins $toff_zero_6b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_AWID]
    connect_bd_net [get_bd_pins $toff_zero_4b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_AWLEN]
    connect_bd_net [get_bd_pins $toff_zero_3b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_AWSIZE]
    connect_bd_net [get_bd_pins $toff_zero_1b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_AWVALID]
    connect_bd_net [get_bd_pins $toff_zero_256b/dout] [get_bd_pins hbm_0/AXI_${saxi}_WDATA]
    connect_bd_net [get_bd_pins $toff_zero_1b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_WLAST]
    connect_bd_net [get_bd_pins $toff_zero_32b/dout]  [get_bd_pins hbm_0/AXI_${saxi}_WSTRB]
    connect_bd_net [get_bd_pins $toff_zero_1b/dout]   [get_bd_pins hbm_0/AXI_${saxi}_WVALID]
    connect_bd_net [get_bd_pins $toff_one_1b/dout]    [get_bd_pins hbm_0/AXI_${saxi}_BREADY]
    connect_bd_net [get_bd_pins $toff_one_1b/dout]    [get_bd_pins hbm_0/AXI_${saxi}_RREADY]
  }

  # ===========================================================================
  # The BSV NF
  # ===========================================================================
  set nf_0 [create_bd_cell -type ip -vlnv nus.edu.sg:bsv:mkVectorAvgNF:1.0 nf_0]

  # ===========================================================================
  # Boundary guard register slices -- pinned by floorplan.xdc into
  # EXCLUDE_PLACEMENT guard pblocks hugging the au50 partpin columns. One
  # RP-side slice per timing-critical boundary interface. Signal set confirmed
  # against src/rp_blk.v: AXI-MM ports carry ar/awsize+qos/cache/lock/prot but
  # NO region; s_axil has NO prot/wstrb.
  # ===========================================================================
  foreach mm_rs {axi_regsl_dma axi_regsl_pcie} {
    set rs [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_register_slice:2.1 $mm_rs]
    set_property -dict [list \
      CONFIG.ADDR_WIDTH {64} \
      CONFIG.DATA_WIDTH {512} \
      CONFIG.HAS_BRESP {1} \
      CONFIG.HAS_BURST {1} \
      CONFIG.HAS_CACHE {1} \
      CONFIG.HAS_LOCK {1} \
      CONFIG.HAS_PROT {1} \
      CONFIG.HAS_QOS {1} \
      CONFIG.HAS_REGION {0} \
      CONFIG.HAS_RRESP {1} \
      CONFIG.HAS_WSTRB {1} \
      CONFIG.ID_WIDTH {2} \
      CONFIG.MAX_BURST_LENGTH {256} \
      CONFIG.PROTOCOL {AXI4} \
      CONFIG.READ_WRITE_MODE {READ_WRITE} \
      CONFIG.SUPPORTS_NARROW_BURST {1} \
    ] $rs
  }

  set axil_regsl [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_register_slice:2.1 axil_regsl]
  set_property -dict [list \
    CONFIG.ADDR_WIDTH {32} \
    CONFIG.DATA_WIDTH {32} \
    CONFIG.HAS_BRESP {1} \
    CONFIG.HAS_BURST {0} \
    CONFIG.HAS_CACHE {0} \
    CONFIG.HAS_LOCK {0} \
    CONFIG.HAS_PROT {0} \
    CONFIG.HAS_QOS {0} \
    CONFIG.HAS_REGION {0} \
    CONFIG.HAS_RRESP {1} \
    CONFIG.HAS_WSTRB {0} \
    CONFIG.PROTOCOL {AXI4LITE} \
    CONFIG.READ_WRITE_MODE {READ_WRITE} \
    CONFIG.SUPPORTS_NARROW_BURST {0} \
  ] $axil_regsl

  # AXIS boundary guards (full register, REG_CONFIG 8) -- 2 in (rph2c, ethrx0),
  # 2 out (rpout0, rpout1).
  foreach rp_rs {axis_regsl_rph2c axis_regsl_ethrx0 axis_regsl_rpout0 axis_regsl_rpout1} {
    set rs [create_bd_cell -type ip -vlnv xilinx.com:ip:axis_register_slice:1.1 $rp_rs]
    set_property -dict [list \
      CONFIG.HAS_TKEEP {1} \
      CONFIG.HAS_TLAST {1} \
      CONFIG.HAS_TREADY {1} \
      CONFIG.HAS_TSTRB {1} \
      CONFIG.REG_CONFIG {8} \
      CONFIG.TDATA_NUM_BYTES {64} \
      CONFIG.TDEST_WIDTH {16} \
      CONFIG.TID_WIDTH {16} \
      CONFIG.TUSER_WIDTH {32} \
    ] $rs
  }

  # ===========================================================================
  # SmartConnect — host-DMA preload fanout (1 SI, 3 MI)
  # ===========================================================================
  set dma_sc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 dma_sc]
  set_property -dict [list \
    CONFIG.NUM_SI   {1} \
    CONFIG.NUM_MI   {3} \
    CONFIG.NUM_CLKS {1} \
  ] $dma_sc

  # Per-channel 2:1 arbiter (SI0 = NF read master, SI1 = host-DMA preload)
  foreach ch {00 02 04} {
    set sc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 hbm_sc_$ch]
    set_property -dict [list \
      CONFIG.NUM_SI   {2} \
      CONFIG.NUM_MI   {1} \
      CONFIG.NUM_CLKS {1} \
    ] $sc
  }

  # Per-channel paths for SAXI_00 / 02 / 04
  foreach saxi {00 02 04} {
    create_hier_cell_path [current_bd_instance .] path_$saxi
  }

  # ===========================================================================
  # SmartConnect — AXI-Lite fanout (1 SI, 3 MI, 2 clocks)
  #   M00 -> nf_0/s_axil   M01 -> apb_bridge_hbm   M02 -> axi_gpio_0
  # ===========================================================================
  set axil_sc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 axil_sc]
  set_property -dict [list \
    CONFIG.NUM_SI   {1} \
    CONFIG.NUM_MI   {3} \
    CONFIG.NUM_CLKS {2} \
  ] $axil_sc

  set axi_gpio_0 [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0]
  set_property -dict [list \
    CONFIG.C_GPIO_WIDTH {32} \
    CONFIG.C_ALL_INPUTS {1} \
  ] $axi_gpio_0

  set apb_bridge_hbm [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_apb_bridge:3.0 apb_bridge_hbm]
  set_property -dict [list \
    CONFIG.C_APB_NUM_SLAVES   {1} \
    CONFIG.C_M_APB_PROTOCOL   {apb3} \
  ] $apb_bridge_hbm

  # ===========================================================================
  # AXIS ingress merge (2:1) + egress demux (1:2 by tdest[15]) around the NF.
  # ARB_ON_MAX_XFERS must stay 0 with ARB_ON_TLAST 1 (ARB_ON_TLAST alone
  # re-arbitrates every beat instead of every packet).
  # ===========================================================================
  set rp_in_sw [create_bd_cell -type ip -vlnv xilinx.com:ip:axis_switch:1.1 rp_in_sw]
  set_property -dict [list \
    CONFIG.ARB_ON_MAX_XFERS {0} \
    CONFIG.ARB_ON_TLAST {1} \
    CONFIG.HAS_TKEEP {1} \
    CONFIG.HAS_TLAST {1} \
    CONFIG.HAS_TSTRB {1} \
    CONFIG.M00_AXIS_BASETDEST {0x00000000} \
    CONFIG.M00_AXIS_HIGHTDEST {0x0000ffff} \
    CONFIG.NUM_MI {1} \
    CONFIG.NUM_SI {2} \
    CONFIG.TDATA_NUM_BYTES {64} \
    CONFIG.TDEST_WIDTH {16} \
    CONFIG.TID_WIDTH {16} \
    CONFIG.TUSER_WIDTH {32} \
  ] $rp_in_sw

  # 1:2 demux by tdest[15]: host C2H range 0x0000-0x7fff -> M00 (rpout0),
  # RP/loopback range 0x8000-0xffff -> M01 (rpout1). NUM_SI=1 -> ARB_ON_* N/A.
  set rp_out_sw [create_bd_cell -type ip -vlnv xilinx.com:ip:axis_switch:1.1 rp_out_sw]
  set_property -dict [list \
    CONFIG.HAS_TKEEP {1} \
    CONFIG.HAS_TLAST {1} \
    CONFIG.HAS_TSTRB {1} \
    CONFIG.M00_AXIS_BASETDEST {0x00000000} \
    CONFIG.M00_AXIS_HIGHTDEST {0x00007fff} \
    CONFIG.M01_AXIS_BASETDEST {0x00008000} \
    CONFIG.M01_AXIS_HIGHTDEST {0x0000ffff} \
    CONFIG.NUM_MI {2} \
    CONFIG.NUM_SI {1} \
    CONFIG.TDATA_NUM_BYTES {64} \
    CONFIG.TDEST_WIDTH {16} \
    CONFIG.TID_WIDTH {16} \
    CONFIG.TUSER_WIDTH {32} \
  ] $rp_out_sw

  # ===========================================================================
  # s_axi_pcie scratchpad — 4 KB BRAM (BAR4), insulated via SmartConnect.
  # ===========================================================================
  set scratch_sc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 scratch_sc]
  set_property -dict [list \
    CONFIG.NUM_SI   {1} \
    CONFIG.NUM_MI   {1} \
    CONFIG.NUM_CLKS {1} \
  ] $scratch_sc
  set scratch_bram_ctrl [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl:4.1 scratch_bram_ctrl]
  set_property -dict [list \
    CONFIG.DATA_WIDTH       {512} \
    CONFIG.READ_LATENCY     {2} \
    CONFIG.SINGLE_PORT_BRAM {1} \
  ] $scratch_bram_ctrl
  set scratch_bram [create_bd_cell -type ip -vlnv xilinx.com:ip:blk_mem_gen:8.4 scratch_bram]
  set_property CONFIG.PRIM_type_to_Implement {BRAM} $scratch_bram

  # ===========================================================================
  # Init/cattrip status aggregation -> axi_gpio_0/gpio_io_i
  # gpio_io_i = { 30'h0, cattrip, init_complete }
  # ===========================================================================
  set status_concat [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat:2.1 status_concat]
  set_property -dict [list \
    CONFIG.NUM_PORTS {3} \
    CONFIG.IN0_WIDTH {1} \
    CONFIG.IN1_WIDTH {1} \
    CONFIG.IN2_WIDTH {30} \
  ] $status_concat

  set status_pad [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 status_pad]
  set_property -dict [list CONFIG.CONST_WIDTH {30} CONFIG.CONST_VAL {0}] $status_pad

  # ===========================================================================
  # Interface connections
  # ===========================================================================
  # DMA -> guard slice -> dma_sc -> per-channel 2:1 arbiter S01
  connect_bd_intf_net [get_bd_intf_ports s_axi_dma]         [get_bd_intf_pins axi_regsl_dma/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins axi_regsl_dma/M_AXI] [get_bd_intf_pins dma_sc/S00_AXI]
  connect_bd_intf_net [get_bd_intf_pins dma_sc/M00_AXI] [get_bd_intf_pins hbm_sc_00/S01_AXI]
  connect_bd_intf_net [get_bd_intf_pins dma_sc/M01_AXI] [get_bd_intf_pins hbm_sc_02/S01_AXI]
  connect_bd_intf_net [get_bd_intf_pins dma_sc/M02_AXI] [get_bd_intf_pins hbm_sc_04/S01_AXI]

  # NF HBM read masters -> per-channel arbiter SI0
  connect_bd_intf_net [get_bd_intf_pins nf_0/hbm_axi_0] [get_bd_intf_pins hbm_sc_00/S00_AXI]
  connect_bd_intf_net [get_bd_intf_pins nf_0/hbm_axi_1] [get_bd_intf_pins hbm_sc_02/S00_AXI]
  connect_bd_intf_net [get_bd_intf_pins nf_0/hbm_axi_2] [get_bd_intf_pins hbm_sc_04/S00_AXI]

  # arbiter -> path -> HBM SAXI
  connect_bd_intf_net [get_bd_intf_pins hbm_sc_00/M00_AXI] [get_bd_intf_pins path_00/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins hbm_sc_02/M00_AXI] [get_bd_intf_pins path_02/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins hbm_sc_04/M00_AXI] [get_bd_intf_pins path_04/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins path_00/M_AXI] -boundary_type upper [get_bd_intf_pins hbm_0/SAXI_00]
  connect_bd_intf_net [get_bd_intf_pins path_02/M_AXI] -boundary_type upper [get_bd_intf_pins hbm_0/SAXI_02]
  connect_bd_intf_net [get_bd_intf_pins path_04/M_AXI] -boundary_type upper [get_bd_intf_pins hbm_0/SAXI_04]

  # AXIS ingress: rph2c/ethrx0 -> [guard] -> rp_in_sw -> nf_0
  connect_bd_intf_net [get_bd_intf_ports s_axis_rph2c]           [get_bd_intf_pins axis_regsl_rph2c/S_AXIS]
  connect_bd_intf_net [get_bd_intf_ports s_axis_ethrx0]          [get_bd_intf_pins axis_regsl_ethrx0/S_AXIS]
  connect_bd_intf_net [get_bd_intf_pins axis_regsl_rph2c/M_AXIS]  [get_bd_intf_pins rp_in_sw/S00_AXIS]
  connect_bd_intf_net [get_bd_intf_pins axis_regsl_ethrx0/M_AXIS] [get_bd_intf_pins rp_in_sw/S01_AXIS]
  connect_bd_intf_net [get_bd_intf_pins rp_in_sw/M00_AXIS]       [get_bd_intf_pins nf_0/s_axis_rpin]

  # AXIS egress: nf_0 -> rp_out_sw -> [guard] -> rpout0/1
  connect_bd_intf_net [get_bd_intf_pins nf_0/m_axis_rpout]       [get_bd_intf_pins rp_out_sw/S00_AXIS]
  connect_bd_intf_net [get_bd_intf_pins rp_out_sw/M00_AXIS]      [get_bd_intf_pins axis_regsl_rpout0/S_AXIS]
  connect_bd_intf_net [get_bd_intf_pins rp_out_sw/M01_AXIS]      [get_bd_intf_pins axis_regsl_rpout1/S_AXIS]
  connect_bd_intf_net [get_bd_intf_pins axis_regsl_rpout0/M_AXIS] [get_bd_intf_ports m_axis_rpout0]
  connect_bd_intf_net [get_bd_intf_pins axis_regsl_rpout1/M_AXIS] [get_bd_intf_ports m_axis_rpout1]

  # m_axibr (NF notification) -> external master port, direct.
  connect_bd_intf_net [get_bd_intf_pins nf_0/m_axibr] [get_bd_intf_ports m_axibr]

  # s_axi_pcie -> guard slice -> scratch
  connect_bd_intf_net [get_bd_intf_ports s_axi_pcie]         [get_bd_intf_pins axi_regsl_pcie/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins axi_regsl_pcie/M_AXI] [get_bd_intf_pins scratch_sc/S00_AXI]
  connect_bd_intf_net [get_bd_intf_pins scratch_sc/M00_AXI] [get_bd_intf_pins scratch_bram_ctrl/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins scratch_bram_ctrl/BRAM_PORTA] [get_bd_intf_pins scratch_bram/BRAM_PORTA]

  # s_axil -> guard slice -> axil_sc -> { nf_0/s_axil ; apb_bridge -> SAPB_0 ; gpio }
  connect_bd_intf_net [get_bd_intf_ports s_axil]          [get_bd_intf_pins axil_regsl/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins axil_regsl/M_AXI] [get_bd_intf_pins axil_sc/S00_AXI]
  connect_bd_intf_net [get_bd_intf_pins axil_sc/M00_AXI] [get_bd_intf_pins nf_0/s_axil]
  connect_bd_intf_net [get_bd_intf_pins axil_sc/M01_AXI] [get_bd_intf_pins apb_bridge_hbm/AXI4_LITE]
  connect_bd_intf_net [get_bd_intf_pins axil_sc/M02_AXI] [get_bd_intf_pins axi_gpio_0/S_AXI]
  connect_bd_intf_net [get_bd_intf_pins apb_bridge_hbm/APB_M] [get_bd_intf_pins hbm_0/SAPB_0]

  # ===========================================================================
  # Net (clock/reset/status) connections
  # ===========================================================================
  # User-clock (200 MHz) domain
  connect_bd_net [get_bd_ports CLK] \
    [get_bd_pins nf_0/CLK] \
    [get_bd_pins axi_regsl_dma/aclk] \
    [get_bd_pins axi_regsl_pcie/aclk] \
    [get_bd_pins axil_regsl/aclk] \
    [get_bd_pins axis_regsl_rph2c/aclk] \
    [get_bd_pins axis_regsl_ethrx0/aclk] \
    [get_bd_pins axis_regsl_rpout0/aclk] \
    [get_bd_pins axis_regsl_rpout1/aclk] \
    [get_bd_pins dma_sc/aclk] \
    [get_bd_pins hbm_sc_00/aclk] \
    [get_bd_pins hbm_sc_02/aclk] \
    [get_bd_pins hbm_sc_04/aclk] \
    [get_bd_pins path_00/aclk_user] \
    [get_bd_pins path_02/aclk_user] \
    [get_bd_pins path_04/aclk_user] \
    [get_bd_pins scratch_sc/aclk] \
    [get_bd_pins scratch_bram_ctrl/s_axi_aclk] \
    [get_bd_pins rp_in_sw/aclk] \
    [get_bd_pins rp_out_sw/aclk] \
    [get_bd_pins axil_sc/aclk] \
    [get_bd_pins axi_gpio_0/s_axi_aclk]
  connect_bd_net [get_bd_ports RST_N] \
    [get_bd_pins nf_0/RST_N] \
    [get_bd_pins axi_regsl_dma/aresetn] \
    [get_bd_pins axi_regsl_pcie/aresetn] \
    [get_bd_pins axil_regsl/aresetn] \
    [get_bd_pins axis_regsl_rph2c/aresetn] \
    [get_bd_pins axis_regsl_ethrx0/aresetn] \
    [get_bd_pins axis_regsl_rpout0/aresetn] \
    [get_bd_pins axis_regsl_rpout1/aresetn] \
    [get_bd_pins dma_sc/aresetn] \
    [get_bd_pins hbm_sc_00/aresetn] \
    [get_bd_pins hbm_sc_02/aresetn] \
    [get_bd_pins hbm_sc_04/aresetn] \
    [get_bd_pins path_00/aresetn_user] \
    [get_bd_pins path_02/aresetn_user] \
    [get_bd_pins path_04/aresetn_user] \
    [get_bd_pins scratch_sc/aresetn] \
    [get_bd_pins scratch_bram_ctrl/s_axi_aresetn] \
    [get_bd_pins rp_in_sw/aresetn] \
    [get_bd_pins rp_out_sw/aresetn] \
    [get_bd_pins axil_sc/aresetn] \
    [get_bd_pins axi_gpio_0/s_axi_aresetn]

  # HBM AXI clock (450 MHz) — HBM IP's 32 AXI_NN_ACLK + path_NN HBM-side stage.
  set hbm_axi_aclk_pins [list]
  for {set i 0} {$i < 32} {incr i} {
    lappend hbm_axi_aclk_pins [get_bd_pins -quiet hbm_0/AXI_[format %02d $i]_ACLK]
  }
  connect_bd_net [get_bd_pins hbm_mmcm_i0/hbm_axiclk] \
    [get_bd_pins path_00/aclk_hbm] \
    [get_bd_pins path_02/aclk_hbm] \
    [get_bd_pins path_04/aclk_hbm] \
    [get_bd_pins hbm_proc_rst/slowest_sync_clk] \
    {*}$hbm_axi_aclk_pins

  # HBM AXI reset (sync to hbm_axiclk, from RST_N + hbm_mmcm_i0/locked)
  connect_bd_net [get_bd_ports RST_N]             [get_bd_pins hbm_proc_rst/ext_reset_in]
  connect_bd_net [get_bd_pins hbm_mmcm_i0/locked] [get_bd_pins hbm_proc_rst/dcm_locked]
  set hbm_axi_arstn_pins [list]
  for {set i 0} {$i < 32} {incr i} {
    lappend hbm_axi_arstn_pins [get_bd_pins -quiet hbm_0/AXI_[format %02d $i]_ARESET_N]
  }
  connect_bd_net [get_bd_pins hbm_proc_rst/peripheral_aresetn] \
    [get_bd_pins path_00/aresetn_hbm] \
    [get_bd_pins path_02/aresetn_hbm] \
    [get_bd_pins path_04/aresetn_hbm] \
    {*}$hbm_axi_arstn_pins

  # HBM ref clock (100 MHz)
  connect_bd_net [get_bd_pins hbm_mmcm_i0/hbm_refclk] [get_bd_pins hbm_0/HBM_REF_CLK_0]

  # APB clock (100 MHz) for HBM SAPB_0 + axi_apb_bridge + axil_sc 2nd clock
  connect_bd_net [get_bd_pins hbm_mmcm_i0/hbm_apbclk] \
    [get_bd_pins hbm_0/APB_0_PCLK] \
    [get_bd_pins apb_bridge_hbm/s_axi_aclk] \
    [get_bd_pins apb_proc_rst/slowest_sync_clk] \
    [get_bd_pins axil_sc/aclk1]
  connect_bd_net [get_bd_ports RST_N]             [get_bd_pins apb_proc_rst/ext_reset_in]
  connect_bd_net [get_bd_pins hbm_mmcm_i0/locked] [get_bd_pins apb_proc_rst/dcm_locked]
  connect_bd_net [get_bd_pins apb_proc_rst/peripheral_aresetn] \
    [get_bd_pins hbm_0/APB_0_PRESET_N] \
    [get_bd_pins apb_bridge_hbm/s_axi_aresetn]

  # Status to GPIO: { 30'h0, cattrip, init_complete }
  connect_bd_net [get_bd_pins hbm_0/apb_complete_0]      [get_bd_pins status_concat/In0]
  connect_bd_net [get_bd_pins hbm_0/DRAM_0_STAT_CATTRIP] [get_bd_pins status_concat/In1]
  connect_bd_net [get_bd_pins status_pad/dout]           [get_bd_pins status_concat/In2]
  connect_bd_net [get_bd_pins status_concat/dout]        [get_bd_pins axi_gpio_0/gpio_io_i]

  # ===========================================================================
  # Address segments
  # ===========================================================================
  # s_axil: nf_0 regs (64 KB) | axi_gpio_0 (64 KB) | HBM SAPB_0 (16 KB)
  assign_bd_address -offset 0x00000000 -range 0x00010000 \
    -target_address_space [get_bd_addr_spaces s_axil] \
    [get_bd_addr_segs nf_0/s_axil/reg0] -force
  assign_bd_address -offset 0x00010000 -range 0x00010000 \
    -target_address_space [get_bd_addr_spaces s_axil] \
    [get_bd_addr_segs axi_gpio_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x00100000 -range 0x00004000 \
    -target_address_space [get_bd_addr_spaces s_axil] \
    [get_bd_addr_segs hbm_0/SAPB_0/Reg] -force

  # s_axi_pcie: 4 KB scratchpad at 0
  assign_bd_address -offset 0x00000000 -range 0x00001000 \
    -target_address_space [get_bd_addr_spaces s_axi_pcie] \
    [get_bd_addr_segs scratch_bram_ctrl/S_AXI/Mem0] -force

  # HBM addressing (lateral switch OFF -> each used SAXI commands its whole MC).
  # The HBM IP fixes SAXI_NN at NN*PC bytes; host (s_axi_dma) and NF
  # (nf_0/hbm_axi_N) use the SAME fixed offset so off_chN in the cuckoo value is
  # the HBM-absolute byte offset (symmetric host/NF contract).
  set hbm_pc_bytes 0x10000000                   ;# 256 MB  (8 GB parts)
  set hbm_mc_bytes [expr {2 * $hbm_pc_bytes}]   ;# MC = 2 pseudo-channels

  # Host-DMA preload view (each channel's HBM SAXI tiled in s_axi_dma space).
  foreach saxi {00 02 04} {
    set seg [get_bd_addr_segs -of_objects [get_bd_intf_pins hbm_0/SAXI_${saxi}]]
    set offset [expr {$hbm_pc_bytes * [scan $saxi "%d"]}]
    assign_bd_address -offset $offset -range $hbm_mc_bytes \
      -target_address_space [get_bd_addr_spaces s_axi_dma] \
      $seg -force
  }

  # NF read-master view (same fixed offsets as the host preload).
  foreach {idx saxi} {0 00 1 02 2 04} {
    set seg [get_bd_addr_segs -of_objects [get_bd_intf_pins hbm_0/SAXI_${saxi}]]
    set offset [expr {$hbm_pc_bytes * [scan $saxi "%d"]}]
    assign_bd_address -offset $offset -range $hbm_mc_bytes \
      -target_address_space [get_bd_addr_spaces nf_0/hbm_axi_${idx}] \
      $seg -force
  }

  # SAXI_01/03/05 are null-tied internally (no external space -> no assignment).

  # ===========================================================================
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name
}

cr_bd_rp_user ""
